spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_booking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  liquibase:
    change-log: db.changelog/db.changelog-master.yml

app:
  image:
    bucket: C:/Users/ASUS ROG/IdeaProjects/my-first-app/images


